import { createHash, randomUUID } from 'node:crypto'
import { mkdir, rename, rm, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import AdmZip from 'adm-zip'
import type { AuditPackageWriterPort } from '../ports/outbound.js'

function stableJson(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`
}

export class AuditPackageAdapter implements AuditPackageWriterPort {
  readonly id = 'adapter.audit-package-zip'

  constructor(private readonly outputDirectory: string) {}

  async write(input: Parameters<AuditPackageWriterPort['write']>[0]): Promise<{
    packageId: string
    absolutePath: string
    contentHash: string
    manifest: Record<string, unknown>
  }> {
    const packageIdentity = createHash('sha256').update(stableJson({
      snapshotId: input.snapshot.snapshotId,
      snapshotHash: input.snapshot.contentHash,
      evidenceIds: [...input.evidenceIds].sort(),
      phaseIds: [...(input.phaseIds ?? [])].sort(),
      includeFindings: input.includeFindings,
      includeReviews: input.includeReviews,
      requestedName: input.requestedName ?? '',
    })).digest('hex')
    const packageId = `PKG-${packageIdentity.slice(0, 16).toUpperCase()}`
    const selected = input.snapshot.evidence.filter((record) => input.evidenceIds.includes(record.id))
    const selectedIds = new Set(selected.map((record) => record.id))
    const selectedPhases = input.phaseIds ? new Set(input.phaseIds) : undefined
    const findings = input.includeFindings
      ? input.snapshot.findings.filter((finding) => selectedPhases
        ? selectedPhases.has(finding.phase)
        : finding.evidenceIds.some((id) => selectedIds.has(id)))
      : []
    const reviews = input.includeReviews
      ? input.snapshot.reviews.filter((review) => selectedPhases
        ? selectedPhases.has(review.phase)
        : selectedIds.has(review.subjectId))
      : []
    const manifest = {
      schemaVersion: '1.0',
      packageId,
      name: input.requestedName ?? `${input.snapshot.workspace.name} audit package`,
      createdAt: input.snapshot.publishedAt,
      workspace: input.snapshot.workspace,
      snapshotId: input.snapshot.snapshotId,
      snapshotHash: input.snapshot.contentHash,
      baselineId: input.snapshot.baselineId,
      scope: {
        phases: [...(input.phaseIds ?? [])].sort(),
        evidenceIds: [...input.evidenceIds].sort(),
      },
      revisionSet: input.snapshot.revisionSet,
      syntheticSample: input.snapshot.workspace.kind === 'sample',
      watermark: input.snapshot.workspace.kind === 'sample'
        ? 'Synthetic sample — not certification evidence'
        : undefined,
      counts: {
        evidence: selected.length,
        findings: findings.length,
        reviews: reviews.length,
      },
      entries: selected.map((record) => ({
        id: record.id,
        revision: record.revision,
        hash: record.hash,
        sourcePath: record.sourcePath,
      })),
    }
    const zip = new AdmZip()
    zip.addFile('manifest.json', Buffer.from(stableJson(manifest)))
    zip.addFile('evidence.json', Buffer.from(stableJson(selected)))
    zip.addFile('findings.json', Buffer.from(stableJson(findings)))
    zip.addFile('reviews.json', Buffer.from(stableJson(reviews)))
    zip.addFile('README.txt', Buffer.from(
      input.snapshot.workspace.kind === 'sample'
        ? 'Synthetic sample — not certification evidence.\n'
        : 'Generated by DO-178C Audit Hub. Validate the manifest and source revisions before use.\n',
    ))
    const stableEntryTime = new Date('1980-01-01T00:00:00.000Z')
    for (const entry of zip.getEntries()) entry.header.time = stableEntryTime
    const bytes = zip.toBuffer()
    const contentHash = createHash('sha256').update(bytes).digest('hex')
    await mkdir(this.outputDirectory, { recursive: true })
    const absolutePath = join(this.outputDirectory, `${packageId}.zip`)
    const temporaryPath = `${absolutePath}.tmp-${randomUUID()}`
    await writeFile(temporaryPath, bytes, { mode: 0o600 })
    await rename(temporaryPath, absolutePath)
    return { packageId, absolutePath, contentHash, manifest }
  }

  async remove(packageIds: string[]): Promise<void> {
    for (const packageId of packageIds) {
      if (!/^PKG-[A-F0-9]{16}$/.test(packageId)) continue
      await rm(join(this.outputDirectory, `${packageId}.zip`), { force: true })
    }
  }
}
