const scenario = (name, result, target = 'overview') => ({
  name,
  actionId: name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''),
  result,
  target,
})

const productTrialSystemsBase = [
  {
    slug: 'do178-review-workbench',
    name: 'DO-178C Review Workbench',
    shortName: 'Review Workbench',
    category: 'Design assurance',
    description: 'Run independent reviews of software lifecycle data and preserve review evidence.',
    workDescription: 'A software reviewer reviews lifecycle data and closes formal review findings.',
    examples: [
      'Review requirement set',
      'Record review finding',
      'Assign finding owner',
      'Verify finding closure',
      'Check objective coverage',
      'Approve review record',
      'Export review evidence',
    ],
    prohibited: 'Never use author approval',
    failureScenario: 'Reject author approval',
    layout: 'review',
    accent: '#7c8cff',
    accentRgb: '124, 140, 255',
    homeTitle: 'Review control',
    eyebrow: 'SOFTWARE REVIEW · SRR-24-017',
    headline: 'Review software design data',
    subhead: 'Review the change set, record objective evidence, and protect reviewer independence.',
    nav: ['Review control', 'Artifact sets', 'Findings', 'Review records'],
    metricPurpose: 'Show review readiness and independence before approval.',
    metrics: [
      ['Review coverage', '92%', '148 of 161 objectives'],
      ['Open findings', '2', 'One high priority'],
      ['Independence', 'Pass', 'All assignments valid'],
      ['Due date', '02 Aug', 'Three workdays'],
    ],
    panels: [
      {
        type: 'table',
        title: 'Review queue',
        subtitle: 'Objective evidence grouped by lifecycle artifact.',
        headers: ['Artifact', 'Revision', 'Coverage', 'State'],
        rows: [
          ['Low-level requirements', 'LLR-18', '48 / 48', 'Ready'],
          ['Software design data', 'SDD-12', '31 / 34', 'Needs review'],
          ['Source code', 'BLD-241', '52 / 55', 'In review'],
          ['Verification cases', 'SVCP-09', '17 / 24', 'Blocked'],
        ],
      },
      {
        type: 'diff',
        title: 'Selected change',
        subtitle: 'LLR-NAV-142 · Prevent stale altitude source',
        before: 'IF source_age > 500 ms THEN use cached altitude.',
        after: 'IF source_age > 500 ms THEN reject the altitude update.',
        note: 'The new rule removes an ambiguous fallback and links to test SVT-NAV-388.',
      },
      {
        type: 'checklist',
        title: 'Review objectives',
        subtitle: '6 of 8 objectives complete.',
        items: [
          ['The requirement is accurate.', true],
          ['The requirement is consistent.', true],
          ['The requirement is verifiable.', true],
          ['The derived requirement is identified.', false],
          ['The trace is complete.', false],
        ],
      },
    ],
    scenarios: [
      scenario('Review requirement set', 'Requirement set opened', 'artifacts'),
      scenario('Record review finding', 'Finding REV-218 recorded', 'findings'),
      scenario('Assign finding owner', 'Finding assigned to Navigation team', 'findings'),
      scenario('Verify finding closure', 'Closure evidence verified', 'findings'),
      scenario('Check objective coverage', 'Objective coverage check passed', 'artifacts'),
      scenario('Approve review record', 'Review record approved', 'records'),
      scenario('Export review evidence', 'Review evidence package exported', 'records'),
      scenario('Reject author approval', 'Author approval rejected', 'records'),
    ],
    reward: 'Assurance increased',
    buyer: 'Software verification lead',
    commercialJob: 'Reduce review effort and produce defensible review records.',
    useFrequency: 'Daily during review and certification increments',
  },
  {
    slug: 'copilot-session-hub',
    name: 'Copilot Sessions',
    shortName: 'Session Hub',
    category: 'Daily productivity',
    description: 'Track Copilot sessions, progress, issues, outputs, and next actions across engineering projects.',
    workDescription: 'An engineering lead tracks Copilot sessions and resolves blocked implementation work.',
    examples: [
      'Start Copilot session',
      'Update session progress',
      'Record session issue',
      'Link branch output',
      'Record next action',
      'Review active sessions',
      'Close completed session',
      'Reopen paused session',
    ],
    prohibited: 'Never delete unresolved session',
    failureScenario: 'Reject unresolved session',
    layout: 'sessions',
    accent: '#8b5cf6',
    accentRgb: '139, 92, 246',
    homeTitle: 'Session command',
    eyebrow: 'ACTIVE COPILOT SESSIONS · TODAY',
    headline: 'Review active sessions',
    subhead: 'Keep every agent run connected to its objective, branch, evidence, and next action.',
    nav: ['Session command', 'Active sessions', 'Issues', 'History'],
    panels: [
      {
        type: 'kanban',
        title: 'Session flow',
        subtitle: 'Work moves from intent to verified completion.',
        columns: [
          ['Running', ['Refine UML routing', 'Add STE prompt gate', 'Audit coverage adapter']],
          ['Needs you', ['Review HIL command API', 'Choose evidence schema']],
          ['Verifying', ['Test Windows package', 'Run medium product walk']],
          ['Complete', ['Fix port alignment', 'Add session recovery']],
        ],
      },
      {
        type: 'timeline',
        title: 'Selected session',
        subtitle: 'Refine UML routing · main · 42 minutes',
        items: [
          ['09:14', 'Started', 'Prompt and repository context accepted.'],
          ['09:28', 'Changed', 'The router now compares four layout strategies.'],
          ['09:43', 'Tested', 'Fourteen stress products have no crossings.'],
          ['09:56', 'Needs review', 'Hospital access retains four crossings.'],
        ],
      },
      {
        type: 'list',
        title: 'Issues to clear',
        subtitle: 'Resolve one issue to restore momentum.',
        items: [
          ['Hospital graph', 'Layout target missed', 'High'],
          ['Windows package', 'Runner is unavailable', 'Medium'],
          ['MATLAB proof', 'Engine is not connected', 'Medium'],
        ],
      },
    ],
    scenarios: [
      scenario('Start Copilot session', 'Session started with packet PKT-204', 'active'),
      scenario('Update session progress', 'Progress updated to 68 percent', 'active'),
      scenario('Record session issue', 'Issue linked to the active session', 'issues'),
      scenario('Link branch output', 'Branch output linked to the session', 'active'),
      scenario('Record next action', 'Next action added to the session', 'active'),
      scenario('Review active sessions', 'Twelve active sessions shown', 'active'),
      scenario('Close completed session', 'Session closed with evidence', 'history'),
      scenario('Reopen paused session', 'Paused session returned to active work', 'active'),
      scenario('Reject unresolved session', 'Unresolved session kept open', 'issues'),
    ],
    reward: 'Momentum gained',
    buyer: 'Engineering lead or senior individual contributor',
    commercialJob: 'Control parallel AI work without losing decisions, blockers, or evidence.',
    useFrequency: 'Multiple times each day',
  },
  {
    slug: 'technical-writing-desk',
    name: 'Technical Writing',
    shortName: 'Writing Desk',
    category: 'Daily productivity',
    description: 'Draft technical content, enforce ASD-STE100, manage comments, and approve controlled documents.',
    workDescription: 'A technical author writes controlled documents and resolves review comments.',
    examples: [
      'Draft technical note',
      'Check STE wording',
      'Compare document revision',
      'Record review comment',
      'Approve controlled revision',
      'Export approved document',
    ],
    prohibited: 'Never use prohibited term',
    failureScenario: 'Reject prohibited term',
    layout: 'writing',
    accent: '#06b6d4',
    accentRgb: '6, 182, 212',
    homeTitle: 'Writing desk',
    eyebrow: 'DESIGN NOTE · DN-FCS-042 · REVISION 7',
    headline: 'Edit flight control note',
    subhead: 'Write clear technical content and resolve review comments without leaving the document.',
    nav: ['Writing desk', 'Documents', 'Review comments', 'Terminology'],
    panels: [
      {
        type: 'editor',
        title: 'Flight control monitoring',
        subtitle: 'Section 4.2 · Source selection',
        paragraphs: [
          'The monitor compares each source with the selected reference.',
          'If the source is stale, the monitor rejects the update.',
          'The monitor records the source identity and the rejection reason.',
        ],
        highlight: 'The monitor records the source identity and the rejection reason.',
      },
      {
        type: 'diagnostics',
        title: 'Writing checks',
        subtitle: 'One blocker and three review items.',
        items: [
          ['STE-TERM-014', 'Use “start” instead of “initiate”.', 'Blocker'],
          ['STE-LEN-006', 'Split this sentence after 25 words.', 'Review'],
          ['LEX-FCS-021', 'Confirm “reference source”.', 'Review'],
          ['TRACE-008', 'Add the linked system requirement.', 'Review'],
        ],
      },
      {
        type: 'comments',
        title: 'Review thread',
        subtitle: 'Independent review · Mina Patel',
        items: [
          ['Mina', 'Does the monitor record the rejected value?', '09:42'],
          ['Tim', 'Yes. I added the value to the rejection record.', '10:03'],
          ['Mina', 'Resolved. Keep the trace to SYS-FCS-118.', '10:11'],
        ],
      },
    ],
    scenarios: [
      scenario('Draft technical note', 'Technical note draft saved', 'documents'),
      scenario('Check STE wording', 'STE check completed with four items', 'terminology'),
      scenario('Compare document revision', 'Revision comparison opened', 'documents'),
      scenario('Record review comment', 'Review comment recorded', 'comments'),
      scenario('Approve controlled revision', 'Controlled revision approved', 'documents'),
      scenario('Export approved document', 'Approved document package exported', 'documents'),
      scenario('Reject prohibited term', 'Prohibited term rejected', 'terminology'),
    ],
    reward: 'Clarity increased',
    buyer: 'Technical author or engineering organisation',
    commercialJob: 'Reduce document review cycles and enforce controlled writing policy.',
    useFrequency: 'Daily',
  },
  {
    slug: 'flight-test-telemetry',
    name: 'Flight Test Telemetry',
    shortName: 'Telemetry Triage',
    category: 'Flight test',
    description: 'Triage recorded telemetry, exceedances, analysis intervals, and investigation evidence.',
    workDescription: 'A flight-test engineer reviews telemetry and prepares an exceedance investigation.',
    examples: [
      'Load telemetry run',
      'Review exceedance event',
      'Mark analysis interval',
      'Compare sensor source',
      'Annotate data dropout',
      'Record engineering note',
      'Export investigation package',
    ],
    prohibited: 'Never show unverified exceedance',
    failureScenario: 'Reject unverified exceedance',
    layout: 'telemetry',
    accent: '#f97316',
    accentRgb: '249, 115, 22',
    homeTitle: 'Telemetry triage',
    eyebrow: 'FLIGHT FT-284 · LEG 03 · 46 MINUTES',
    headline: 'Review acceleration exceedance',
    subhead: 'Correlate aircraft state, mark the valid interval, and preserve the source samples.',
    nav: ['Telemetry triage', 'Runs', 'Events', 'Investigations'],
    metricPurpose: 'Show data health and triage scope for the selected flight.',
    metrics: [
      ['Channels', '248', '244 valid'],
      ['Exceedances', '3', 'One unverified'],
      ['Marked time', '04:18', 'Across six intervals'],
      ['Data health', '98.7%', 'Two short dropouts'],
    ],
    panels: [
      {
        type: 'chart',
        title: 'Normal acceleration',
        subtitle: '09:42:10–09:44:00 · 20 Hz',
        series: [28, 30, 31, 34, 39, 51, 68, 82, 74, 57, 44, 40, 38, 36, 35, 34],
        threshold: 70,
        labels: ['09:42:10', '09:42:40', '09:43:10', '09:43:40'],
      },
      {
        type: 'events',
        title: 'Correlated events',
        subtitle: 'Selected event · EVT-391',
        items: [
          ['09:42:51.220', 'NZ exceeded 2.50 g', 'Open'],
          ['09:42:51.480', 'Pilot input reached 84%', 'Context'],
          ['09:42:52.040', 'Autopilot disconnected', 'Context'],
          ['09:42:55.810', 'NZ returned below limit', 'Clear'],
        ],
      },
      {
        type: 'list',
        title: 'Investigation status',
        subtitle: 'Three facts remain.',
        items: [
          ['Interval', '09:42:49–09:42:58', 'Set'],
          ['Source integrity', 'ADC-A dropout absent', 'Pass'],
          ['Engineering note', 'Awaiting review', 'Open'],
        ],
      },
    ],
    scenarios: [
      scenario('Load telemetry run', 'Flight FT-284 loaded', 'runs'),
      scenario('Review exceedance event', 'Exceedance EVT-391 opened', 'events'),
      scenario('Mark analysis interval', 'Analysis interval marked', 'events'),
      scenario('Compare sensor source', 'Sensor source comparison opened', 'events'),
      scenario('Annotate data dropout', 'Data dropout annotation recorded', 'runs'),
      scenario('Record engineering note', 'Engineering note linked to EVT-391', 'investigations'),
      scenario('Export investigation package', 'Investigation package exported', 'investigations'),
      scenario('Reject unverified exceedance', 'Unverified exceedance withheld', 'events'),
    ],
    reward: 'Signal understood',
    buyer: 'Flight-test engineering lead',
    commercialJob: 'Reduce time from flight data to a reviewable investigation.',
    useFrequency: 'Daily during flight-test campaigns',
  },
  {
    slug: 'aircraft-trade-study',
    name: 'Aircraft Trade Study',
    shortName: 'Trade Study',
    category: 'Engineering analysis',
    description: 'Run MATLAB-backed analyses, compare options, review sensitivity, and approve study baselines.',
    workDescription: 'A performance engineer compares aircraft design options and approves a study baseline.',
    examples: [
      'Define study case',
      'Run performance analysis',
      'Compare design options',
      'Review sensitivity result',
      'Approve study baseline',
    ],
    prohibited: 'Never use stale assumption',
    failureScenario: 'Reject stale assumption',
    layout: 'trade',
    accent: '#22c55e',
    accentRgb: '34, 197, 94',
    homeTitle: 'Trade study',
    eyebrow: 'STUDY TS-CRZ-019 · BASELINE B',
    headline: 'Compare aircraft options',
    subhead: 'Compare performance, weight, and margin with one controlled assumption set.',
    nav: ['Trade study', 'Cases', 'Results', 'Baselines'],
    panels: [
      {
        type: 'scatter',
        title: 'Range versus weight',
        subtitle: 'Each point uses the approved atmospheric model.',
        points: [
          ['A', 22, 72, 'Baseline'],
          ['B', 46, 54, 'Balanced'],
          ['C', 72, 32, 'Recommended'],
          ['D', 84, 66, 'High risk'],
        ],
      },
      {
        type: 'matrix',
        title: 'Option comparison',
        subtitle: 'Weighted result · higher is better.',
        headers: ['Option', 'Range', 'Field length', 'Margin', 'Score'],
        rows: [
          ['A', '3,180 nm', '1,460 m', '+92 kg', '72'],
          ['B', '3,310 nm', '1,510 m', '+148 kg', '84'],
          ['C', '3,420 nm', '1,535 m', '+186 kg', '91'],
          ['D', '3,460 nm', '1,690 m', '+44 kg', '68'],
        ],
      },
      {
        type: 'sensitivity',
        title: 'Sensitivity',
        subtitle: 'Range response around Option C.',
        items: [
          ['Cruise drag', '-118 nm', 82],
          ['Empty weight', '-76 nm', 58],
          ['Fuel reserve', '-54 nm', 41],
          ['Propulsive efficiency', '+96 nm', 71],
        ],
      },
    ],
    scenarios: [
      scenario('Define study case', 'Study case TS-CRZ-019 defined', 'cases'),
      scenario('Run performance analysis', 'Performance analysis completed', 'results'),
      scenario('Compare design options', 'Four design options compared', 'results'),
      scenario('Review sensitivity result', 'Sensitivity result opened', 'results'),
      scenario('Approve study baseline', 'Study baseline B approved', 'baselines'),
      scenario('Reject stale assumption', 'Stale assumption rejected', 'cases'),
    ],
    reward: 'Decision confidence gained',
    buyer: 'Performance engineering manager',
    commercialJob: 'Make engineering analyses repeatable, comparable, and reviewable.',
    useFrequency: 'Weekly and at design gates',
  },
  {
    slug: 'hil-campaign-orchestrator',
    name: 'HIL Test Campaign',
    shortName: 'HIL Campaigns',
    category: 'Verification operations',
    description: 'Reserve benches, load configurations, execute procedures, manage failures, and preserve campaign evidence.',
    workDescription: 'A test engineer runs hardware-in-the-loop campaigns and reviews failed procedures.',
    examples: [
      'Reserve test bench',
      'Load test configuration',
      'Start test campaign',
      'Pause test campaign',
      'Review failed procedure',
      'Retry failed procedure',
      'Approve campaign evidence',
      'Release test bench',
    ],
    prohibited: 'Never use unreserved bench',
    failureScenario: 'Reject unreserved bench',
    layout: 'hil',
    accent: '#eab308',
    accentRgb: '234, 179, 8',
    homeTitle: 'Campaign control',
    eyebrow: 'CAMPAIGN HIL-FCS-088 · NIGHT SHIFT',
    headline: 'Run HIL test campaign',
    subhead: 'Control configuration, procedures, failures, and evidence from one campaign view.',
    nav: ['Campaign control', 'Bench schedule', 'Procedures', 'Evidence'],
    metricPurpose: 'Show campaign progress, bench state, and remaining test time.',
    metrics: [
      ['Procedures', '38 / 52', '73 percent complete'],
      ['Passed', '36', 'Two need review'],
      ['Bench state', 'Running', '04 · FCS rig'],
      ['Time remaining', '02:18', 'Finish at 03:42'],
    ],
    panels: [
      {
        type: 'schedule',
        title: 'Bench schedule',
        subtitle: 'Reserved assets and current campaign state.',
        rows: [
          ['Bench 01', 'Available', 'None', 'Ready'],
          ['Bench 02', 'NAV regression', '01:10', 'Running'],
          ['Bench 03', 'Maintenance', '06:00', 'Blocked'],
          ['Bench 04', 'FCS campaign', '02:18', 'Running'],
        ],
      },
      {
        type: 'pipeline',
        title: 'Current procedure',
        subtitle: 'TC-FCS-118 · Reject invalid air-data source',
        items: [
          ['Load configuration', 'Complete'],
          ['Start real-time model', 'Complete'],
          ['Inject stale source', 'Complete'],
          ['Observe rejection', 'Running'],
          ['Collect evidence', 'Waiting'],
        ],
      },
      {
        type: 'console',
        title: 'Live observations',
        subtitle: 'Time-synchronised bench output.',
        items: [
          '01:23:18.442  source ADC-B marked stale',
          '01:23:18.449  monitor rejected sample 008219',
          '01:23:18.451  source ADC-A remains selected',
          '01:23:18.612  assertion FCS-118-04 passed',
        ],
      },
    ],
    scenarios: [
      scenario('Reserve test bench', 'Bench 04 reserved', 'schedule'),
      scenario('Load test configuration', 'Configuration FCS-24.8 loaded', 'campaign'),
      scenario('Start test campaign', 'Campaign HIL-FCS-088 started', 'campaign'),
      scenario('Pause test campaign', 'Campaign paused at a safe procedure boundary', 'campaign'),
      scenario('Review failed procedure', 'Failed procedure TC-FCS-104 opened', 'procedures'),
      scenario('Retry failed procedure', 'Failed procedure queued for retry', 'procedures'),
      scenario('Approve campaign evidence', 'Campaign evidence approved', 'evidence'),
      scenario('Release test bench', 'Bench 04 released with a clean state', 'schedule'),
      scenario('Reject unreserved bench', 'Unreserved bench request rejected', 'schedule'),
    ],
    reward: 'Campaign progress secured',
    buyer: 'Verification or laboratory manager',
    commercialJob: 'Increase expensive bench utilisation and preserve trustworthy evidence.',
    useFrequency: 'Daily in verification laboratories',
  },
  {
    slug: 'supplier-intake-portal',
    name: 'Supplier Deliveries',
    shortName: 'Supplier Intake',
    category: 'Supply-chain assurance',
    description: 'Validate supplier packages, record gaps, coordinate correction, and control acceptance.',
    workDescription: 'A supplier assurance engineer validates software deliveries and records compliance gaps.',
    examples: [
      'Receive supplier package',
      'Validate package manifest',
      'Review compliance gap',
      'Request supplier correction',
      'Verify corrected package',
      'Accept supplier delivery',
    ],
    prohibited: 'Never use unsigned package',
    failureScenario: 'Reject unsigned package',
    layout: 'supplier',
    accent: '#ec4899',
    accentRgb: '236, 72, 153',
    homeTitle: 'Supplier intake',
    eyebrow: 'DELIVERY SUP-ACU-241 · REVISION 03',
    headline: 'Validate supplier delivery',
    subhead: 'Check identity, completeness, compliance, and provenance before acceptance.',
    nav: ['Supplier intake', 'Deliveries', 'Compliance gaps', 'Suppliers'],
    panels: [
      {
        type: 'intake',
        title: 'Delivery validation',
        subtitle: 'ACU flight-control software · Build 241',
        items: [
          ['Package signature', 'Verified', 'Pass'],
          ['Manifest completeness', '42 of 42 files', 'Pass'],
          ['Configuration identity', 'Matches CIDL-18', 'Pass'],
          ['Compliance statement', 'Section 7 missing', 'Gap'],
          ['Malware scan', 'No findings', 'Pass'],
        ],
      },
      {
        type: 'table',
        title: 'Recent deliveries',
        subtitle: 'Current state by supplier and package.',
        headers: ['Supplier', 'Package', 'Received', 'State'],
        rows: [
          ['Aero Controls', 'ACU-241', '08:14', 'Needs correction'],
          ['Vector Systems', 'NAV-118', '07:52', 'Ready'],
          ['Northstar Labs', 'IOP-066', 'Yesterday', 'Accepted'],
          ['Actuation Inc.', 'ACE-034', 'Yesterday', 'Quarantined'],
        ],
      },
      {
        type: 'comments',
        title: 'Correction thread',
        subtitle: 'Gap GAP-ACU-018',
        items: [
          ['Review', 'The compliance statement does not identify tool TQL-04.', '09:04'],
          ['Supplier', 'We will issue revision 04 before 16:00 UTC.', '09:21'],
          ['Review', 'Keep the package identity and replace only the statement.', '09:28'],
        ],
      },
    ],
    scenarios: [
      scenario('Receive supplier package', 'Supplier package SUP-ACU-241 received', 'deliveries'),
      scenario('Validate package manifest', 'Package manifest validated', 'deliveries'),
      scenario('Review compliance gap', 'Compliance gap GAP-ACU-018 opened', 'gaps'),
      scenario('Request supplier correction', 'Correction request sent to supplier queue', 'gaps'),
      scenario('Verify corrected package', 'Corrected package verification passed', 'deliveries'),
      scenario('Accept supplier delivery', 'Supplier delivery accepted', 'deliveries'),
      scenario('Reject unsigned package', 'Unsigned package quarantined', 'deliveries'),
    ],
    reward: 'Supply risk reduced',
    buyer: 'Supplier assurance or programme quality manager',
    commercialJob: 'Shorten supplier acceptance while retaining defensible provenance.',
    useFrequency: 'Several times each week',
  },
  {
    slug: 'requirements-impact-workbench',
    name: 'Requirement Change Impact',
    shortName: 'Impact Workbench',
    category: 'Change control',
    description: 'Trace requirement changes through design, interfaces, implementation, verification, and approval.',
    workDescription: 'A systems engineer traces requirement changes and controls affected software work.',
    examples: [
      'Import requirement change',
      'Trace affected design',
      'Compare trace revision',
      'Review module impact',
      'Assign rework action',
      'Estimate change effort',
      'Approve impact decision',
    ],
    prohibited: 'Never delete unreviewed impact',
    failureScenario: 'Reject unreviewed impact',
    layout: 'impact',
    accent: '#14b8a6',
    accentRgb: '20, 184, 166',
    homeTitle: 'Change impact',
    eyebrow: 'CHANGE CR-1187 · SYS-NAV-142 · REVISION 6',
    headline: 'Assess requirement change',
    subhead: 'Follow the change from system intent to affected software and verification evidence.',
    nav: ['Change impact', 'Change requests', 'Affected artifacts', 'Decisions'],
    metricPurpose: 'Show the change scope for planning and approval.',
    metrics: [
      ['Affected artifacts', '17', 'Seven need action'],
      ['Affected modules', '4', 'One safety critical'],
      ['Test impact', '6', 'Two new cases'],
      ['Decision state', 'Review', 'Three owners pending'],
    ],
    panels: [
      {
        type: 'graph',
        title: 'Impact path',
        subtitle: 'The selected path reaches implementation and verification.',
        nodes: [
          ['SYS-NAV-142', 'System requirement', 1],
          ['SWR-NAV-388', 'Software requirement', 2],
          ['NAV Monitor', 'Software module', 3],
          ['LLR-NAV-142', 'Low-level requirement', 4],
          ['SVT-NAV-388', 'Verification case', 5],
        ],
      },
      {
        type: 'table',
        title: 'Affected artifacts',
        subtitle: 'Ownership and required action.',
        headers: ['Artifact', 'Owner', 'Impact', 'Action'],
        rows: [
          ['SWR-NAV-388', 'Navigation', 'Content', 'Revise'],
          ['ICD-ADC-014', 'Air data', 'Interface', 'Review'],
          ['MON-NAV', 'Navigation', 'Behavior', 'Revise'],
          ['SVT-NAV-388', 'Verification', 'Coverage', 'Add cases'],
        ],
      },
      {
        type: 'decision',
        title: 'Decision summary',
        subtitle: 'Proposed scope for approval.',
        items: [
          ['Change class', 'Software behavior'],
          ['Safety effect', 'No increase'],
          ['Reapproval', 'Four baselines'],
          ['Estimated work', '14 engineer-days'],
        ],
      },
    ],
    scenarios: [
      scenario('Import requirement change', 'Requirement change CR-1187 imported', 'changes'),
      scenario('Trace affected design', 'Seventeen affected artifacts traced', 'artifacts'),
      scenario('Compare trace revision', 'Trace revision comparison opened', 'artifacts'),
      scenario('Review module impact', 'Four module impacts opened', 'artifacts'),
      scenario('Assign rework action', 'Rework action assigned', 'artifacts'),
      scenario('Estimate change effort', 'Change effort estimate recorded', 'decisions'),
      scenario('Approve impact decision', 'Impact decision approved', 'decisions'),
      scenario('Reject unreviewed impact', 'Unreviewed impact kept open', 'decisions'),
    ],
    reward: 'Change risk contained',
    buyer: 'Systems engineering or configuration management lead',
    commercialJob: 'Reduce change-analysis time and prevent missed downstream work.',
    useFrequency: 'Daily on active programmes',
  },
  {
    slug: 'avionics-load-manager',
    name: 'Software Load Control',
    shortName: 'Load Manager',
    category: 'Configuration control',
    description: 'Control load identity, compatibility, release authorization, installation, and as-loaded evidence.',
    workDescription: 'A configuration manager authorizes software loads and verifies installed aircraft configurations.',
    examples: [
      'Register software load',
      'Check hardware compatibility',
      'Authorize load release',
      'Schedule aircraft load',
      'Record aircraft installation',
      'Verify loaded configuration',
    ],
    prohibited: 'Never use incompatible load',
    failureScenario: 'Reject incompatible load',
    layout: 'load',
    accent: '#3b82f6',
    accentRgb: '59, 130, 246',
    homeTitle: 'Load control',
    eyebrow: 'LOAD FCS-24.8.3 · RELEASE CANDIDATE',
    headline: 'Approve software load',
    subhead: 'Protect aircraft compatibility and retain the exact as-loaded configuration.',
    nav: ['Load control', 'Software loads', 'Aircraft fleet', 'Install records'],
    panels: [
      {
        type: 'release',
        title: 'Release path',
        subtitle: 'Each gate preserves a signed configuration record.',
        items: [
          ['Load identity', 'Complete'],
          ['Compatibility', 'Complete'],
          ['Verification', 'In review'],
          ['Release authority', 'Waiting'],
          ['Fleet installation', 'Waiting'],
        ],
      },
      {
        type: 'compatibility',
        title: 'Compatibility matrix',
        subtitle: 'Load FCS-24.8.3 against installed hardware.',
        headers: ['LRU part', 'Hardware rev', 'Bootloader', 'Result'],
        rows: [
          ['FCCA-410', 'H', '3.12', 'Compatible'],
          ['FCCA-411', 'H', '3.12', 'Compatible'],
          ['FCCA-392', 'F', '2.80', 'Blocked'],
          ['FCCA-425', 'J', '3.14', 'Compatible'],
        ],
      },
      {
        type: 'timeline',
        title: 'Configuration record',
        subtitle: 'Immutable release history.',
        items: [
          ['08:04', 'Registered', 'Manifest hash 8a2f…31c0 recorded.'],
          ['08:22', 'Compared', 'Hardware compatibility rule set 14 passed.'],
          ['09:10', 'Verified', 'Automated evidence set completed.'],
          ['Now', 'Awaiting review', 'Independent verifier must approve.'],
        ],
      },
    ],
    scenarios: [
      scenario('Register software load', 'Software load FCS-24.8.3 registered', 'loads'),
      scenario('Check hardware compatibility', 'Hardware compatibility checked', 'fleet'),
      scenario('Authorize load release', 'Load release authorized', 'loads'),
      scenario('Schedule aircraft load', 'Aircraft load scheduled', 'fleet'),
      scenario('Record aircraft installation', 'Aircraft installation recorded', 'install'),
      scenario('Verify loaded configuration', 'Loaded configuration verified', 'install'),
      scenario('Reject incompatible load', 'Incompatible load rejected', 'fleet'),
    ],
    reward: 'Configuration secured',
    buyer: 'Configuration management or fleet engineering lead',
    commercialJob: 'Prevent incompatible loads and automate as-loaded evidence.',
    useFrequency: 'At every software release and installation',
  },
  {
    slug: 'fracas-investigation',
    name: 'FRACAS Investigations',
    shortName: 'FRACAS',
    category: 'Reliability',
    description: 'Capture failures, analyse causes, control corrective actions, and verify closure.',
    workDescription: 'A reliability engineer investigates failures and verifies corrective action closure.',
    examples: [
      'Record failure report',
      'Classify failure mode',
      'Record containment action',
      'Analyze root cause',
      'Link causal evidence',
      'Assign corrective action',
      'Verify action closure',
      'Monitor failure recurrence',
    ],
    prohibited: 'Never delete open corrective action',
    failureScenario: 'Reject open corrective action',
    layout: 'fracas',
    accent: '#ef4444',
    accentRgb: '239, 68, 68',
    homeTitle: 'Reliability control',
    eyebrow: 'FRACAS · AIR-DATA SYSTEM · LAST 90 DAYS',
    headline: 'Investigate connector failures',
    subhead: 'Connect failure evidence, causal analysis, action ownership, and recurrence monitoring.',
    nav: ['Reliability control', 'Failure reports', 'Investigations', 'Corrective actions'],
    metricPurpose: 'Show reliability risk that changes case priority.',
    metrics: [
      ['Open reports', '24', '+4 this month'],
      ['Critical', '2', 'Both contained'],
      ['Actions overdue', '3', 'Oldest is 11 days'],
      ['Repeat rate', '8.2%', '+1.4 points'],
    ],
    panels: [
      {
        type: 'bars',
        title: 'Failure modes',
        subtitle: 'Pareto view · 90-day rolling window.',
        items: [
          ['Connector intermittency', 84, '18'],
          ['Sensor drift', 58, '12'],
          ['Power transient', 39, '8'],
          ['Software timeout', 28, '6'],
          ['Unknown', 18, '4'],
        ],
      },
      {
        type: 'investigation',
        title: 'Selected investigation',
        subtitle: 'FR-2026-118 · Connector intermittency',
        items: [
          ['Problem', 'ADC-B data drops during high vibration.'],
          ['Containment', 'Inspect and reseat connector before flight.'],
          ['Root cause', 'Backshell torque below process limit.'],
          ['Correction', 'Update assembly tool and inspection step.'],
        ],
      },
      {
        type: 'table',
        title: 'Corrective actions',
        subtitle: 'Ownership and recurrence evidence.',
        headers: ['Action', 'Owner', 'Due', 'State'],
        rows: [
          ['Update torque tool', 'Manufacturing', '01 Aug', 'In work'],
          ['Revise assembly step', 'Process Eng.', '02 Aug', 'Review'],
          ['Inspect fleet sample', 'Quality', '04 Aug', 'Planned'],
          ['Monitor recurrence', 'Reliability', '30 Sep', 'Running'],
        ],
      },
    ],
    scenarios: [
      scenario('Record failure report', 'Failure report FR-2026-118 recorded', 'reports'),
      scenario('Classify failure mode', 'Failure mode classified', 'reports'),
      scenario('Record containment action', 'Containment action recorded', 'actions'),
      scenario('Analyze root cause', 'Root cause analysis opened', 'investigations'),
      scenario('Link causal evidence', 'Causal evidence linked', 'investigations'),
      scenario('Assign corrective action', 'Corrective action assigned', 'actions'),
      scenario('Verify action closure', 'Action closure verified', 'actions'),
      scenario('Monitor failure recurrence', 'Recurrence monitor started', 'reports'),
      scenario('Reject open corrective action', 'Open corrective action retained', 'actions'),
    ],
    reward: 'Reliability improved',
    buyer: 'Reliability, quality, or safety manager',
    commercialJob: 'Shorten failure closure and detect recurrence before it becomes systemic.',
    useFrequency: 'Daily',
  },
]

const architecturePlans = {
  'do178-review-workbench': {
    structure: 'Experience-first',
    seedModule: 'Application workflow',
    uiModuleId: 'mod.experience-first',
    style: 'layered review system',
    modules: [
      ['mod.review-control', 'Review control', 'workflow', 'Coordinates independent review tasks and review state.'],
      ['mod.evidence-index', 'Evidence index', 'domain', 'Owns lifecycle data, trace links, revisions, and objective coverage.'],
      ['mod.finding-control', 'Finding control', 'domain', 'Owns findings, ownership, closure evidence, and review rules.'],
      ['mod.review-records', 'Review records', 'platform', 'Preserves approved review records and immutable evidence.'],
    ],
    dependencies: [
      ['mod.experience-first', 'mod.review-control', 'The reviewer workspace starts approved review operations.'],
      ['mod.review-control', 'mod.evidence-index', 'Review tasks read controlled lifecycle evidence.'],
      ['mod.review-control', 'mod.finding-control', 'Review tasks create and resolve formal findings.'],
      ['mod.finding-control', 'mod.review-records', 'Verified closure creates an immutable review record.'],
    ],
  },
  'copilot-session-hub': {
    structure: 'Domain-centered',
    seedModule: 'Core domain',
    uiModuleId: 'mod.session-workspace',
    style: 'event-driven work tracker',
    modules: [
      ['mod.session-workspace', 'Session workspace', 'experience', 'Shows active agent work, decisions, issues, and next actions.'],
      ['mod.session-ledger', 'Session ledger', 'domain', 'Owns session identity, state, progress, and history.'],
      ['mod.issue-queue', 'Issue queue', 'workflow', 'Routes blockers, decisions, and review requests.'],
      ['mod.evidence-store', 'Evidence store', 'platform', 'Preserves outputs, links, checks, and completion evidence.'],
    ],
    dependencies: [
      ['mod.session-workspace', 'mod.session-ledger', 'The workspace reads and updates session state.'],
      ['mod.session-ledger', 'mod.issue-queue', 'Blocked sessions create queue items.'],
      ['mod.session-ledger', 'mod.evidence-store', 'Completed sessions write evidence.'],
      ['mod.issue-queue', 'mod.evidence-store', 'Resolved issues retain their decision evidence.'],
    ],
  },
  'technical-writing-desk': {
    structure: 'Experience-first',
    seedModule: 'Application workflow',
    uiModuleId: 'mod.experience-first',
    style: 'document-centered authoring system',
    modules: [
      ['mod.document-control', 'Document control', 'workflow', 'Coordinates drafts, revisions, reviews, and controlled export.'],
      ['mod.ste-checker', 'STE checker', 'domain', 'Applies approved terminology and ASD-STE100 writing rules.'],
      ['mod.comment-service', 'Comment service', 'domain', 'Owns review threads, decisions, and resolution state.'],
    ],
    dependencies: [
      ['mod.experience-first', 'mod.document-control', 'The editor starts document operations.'],
      ['mod.document-control', 'mod.ste-checker', 'Drafts pass the writing policy before approval.'],
      ['mod.document-control', 'mod.comment-service', 'Controlled revisions retain review comments.'],
    ],
  },
  'flight-test-telemetry': {
    structure: 'Focused core',
    seedModule: 'Core workflow',
    uiModuleId: 'mod.telemetry-console',
    style: 'stream-processing investigation system',
    modules: [
      ['mod.telemetry-console', 'Telemetry console', 'experience', 'Synchronizes plots, events, intervals, and investigation controls.'],
      ['mod.run-ingest', 'Run ingest', 'connection', 'Reads recorded channels and validates time and source identity.'],
      ['mod.signal-analysis', 'Signal analysis', 'domain', 'Computes thresholds, dropouts, and correlated events.'],
      ['mod.investigation', 'Investigation', 'workflow', 'Owns intervals, engineering notes, review, and export.'],
      ['mod.flight-archive', 'Flight archive', 'platform', 'Preserves source samples and investigation packages.'],
    ],
    dependencies: [
      ['mod.telemetry-console', 'mod.run-ingest', 'The console requests a recorded flight run.'],
      ['mod.run-ingest', 'mod.signal-analysis', 'Validated samples enter signal analysis.'],
      ['mod.signal-analysis', 'mod.investigation', 'Verified events start an investigation.'],
      ['mod.investigation', 'mod.flight-archive', 'The investigation retains source evidence.'],
    ],
  },
  'aircraft-trade-study': {
    structure: 'Domain-centered',
    seedModule: 'Core domain',
    uiModuleId: 'mod.study-canvas',
    style: 'analysis pipeline',
    modules: [
      ['mod.study-canvas', 'Study canvas', 'experience', 'Owns parameter editing, result comparison, and decision views.'],
      ['mod.case-control', 'Case control', 'domain', 'Owns cases, assumptions, units, and approved baselines.'],
      ['mod.model-runner', 'Model runner', 'connection', 'Runs the approved analysis model and captures execution data.'],
      ['mod.trade-engine', 'Trade engine', 'domain', 'Computes comparison, sensitivity, margin, and rank.'],
    ],
    dependencies: [
      ['mod.study-canvas', 'mod.case-control', 'The canvas edits controlled study cases.'],
      ['mod.study-canvas', 'mod.trade-engine', 'The canvas requests traceable comparison results.'],
      ['mod.case-control', 'mod.model-runner', 'Approved case inputs start model runs.'],
      ['mod.model-runner', 'mod.trade-engine', 'Model outputs enter the trade calculation.'],
    ],
  },
  'hil-campaign-orchestrator': {
    structure: 'Focused core',
    seedModule: 'Core workflow',
    uiModuleId: 'mod.campaign-console',
    style: 'distributed execution control',
    modules: [
      ['mod.campaign-console', 'Campaign console', 'experience', 'Shows reservations, execution state, failures, and evidence.'],
      ['mod.bench-scheduler', 'Bench scheduler', 'domain', 'Owns reservations, conflicts, assets, and campaign windows.'],
      ['mod.test-executor', 'Test executor', 'workflow', 'Loads configurations and controls procedure execution.'],
      ['mod.rig-adapter', 'Rig adapter', 'connection', 'Isolates real-time bench commands and observations.'],
      ['mod.campaign-evidence', 'Campaign evidence', 'platform', 'Stores results, logs, configurations, and approvals.'],
    ],
    dependencies: [
      ['mod.campaign-console', 'mod.bench-scheduler', 'The console reserves a valid test asset.'],
      ['mod.bench-scheduler', 'mod.test-executor', 'A valid reservation permits campaign execution.'],
      ['mod.test-executor', 'mod.rig-adapter', 'The executor controls the reserved rig.'],
      ['mod.test-executor', 'mod.campaign-evidence', 'Each procedure writes time-linked evidence.'],
    ],
  },
  'supplier-intake-portal': {
    structure: 'Experience-first',
    seedModule: 'Application workflow',
    uiModuleId: 'mod.experience-first',
    style: 'case-management portal',
    modules: [
      ['mod.intake-flow', 'Intake flow', 'workflow', 'Coordinates submission, checks, correction, and acceptance.'],
      ['mod.package-validator', 'Package validator', 'domain', 'Checks manifests, file integrity, metadata, and required content.'],
      ['mod.gap-control', 'Gap control', 'domain', 'Owns gaps, supplier responses, due dates, and closure.'],
      ['mod.acceptance-records', 'Acceptance records', 'platform', 'Preserves accepted packages and approval evidence.'],
    ],
    dependencies: [
      ['mod.experience-first', 'mod.intake-flow', 'The supplier portal starts intake tasks.'],
      ['mod.intake-flow', 'mod.package-validator', 'Every submission passes deterministic checks.'],
      ['mod.package-validator', 'mod.gap-control', 'Failed checks create controlled gaps.'],
      ['mod.intake-flow', 'mod.acceptance-records', 'Accepted packages create immutable records.'],
    ],
  },
  'requirements-impact-workbench': {
    structure: 'Domain-centered',
    seedModule: 'Core domain',
    uiModuleId: 'mod.impact-workspace',
    style: 'graph-analysis decision system',
    modules: [
      ['mod.impact-workspace', 'Impact workspace', 'experience', 'Shows change scope, trace paths, decisions, and review state.'],
      ['mod.trace-index', 'Trace index', 'platform', 'Indexes requirements, design, code, tests, and approved revisions.'],
      ['mod.impact-engine', 'Impact engine', 'domain', 'Traverses dependencies and classifies affected records.'],
      ['mod.decision-control', 'Decision control', 'workflow', 'Owns dispositions, review assignments, and approval.'],
    ],
    dependencies: [
      ['mod.impact-workspace', 'mod.impact-engine', 'The workspace requests an impact calculation.'],
      ['mod.impact-engine', 'mod.trace-index', 'The engine reads the approved trace graph.'],
      ['mod.impact-engine', 'mod.decision-control', 'Affected records create disposition work.'],
      ['mod.decision-control', 'mod.trace-index', 'Approved decisions update trace review state.'],
    ],
  },
  'avionics-load-manager': {
    structure: 'Focused core',
    seedModule: 'Core workflow',
    uiModuleId: 'mod.release-workspace',
    style: 'transactional release system',
    modules: [
      ['mod.release-workspace', 'Release workspace', 'experience', 'Guides package selection, checks, authorization, and load state.'],
      ['mod.compatibility', 'Compatibility', 'domain', 'Owns hardware, software, aircraft, and configuration rules.'],
      ['mod.load-control', 'Load control', 'workflow', 'Coordinates authorization, transfer, verification, and rollback.'],
      ['mod.target-adapter', 'Target adapter', 'connection', 'Isolates aircraft or bench loading protocols.'],
      ['mod.release-ledger', 'Release ledger', 'platform', 'Preserves package identity, signatures, and installation history.'],
    ],
    dependencies: [
      ['mod.release-workspace', 'mod.compatibility', 'The workspace checks the selected configuration.'],
      ['mod.compatibility', 'mod.load-control', 'A compatible selection permits loading.'],
      ['mod.load-control', 'mod.target-adapter', 'The controller transfers the approved package.'],
      ['mod.load-control', 'mod.release-ledger', 'Each load writes an immutable result.'],
    ],
  },
  'fracas-investigation': {
    structure: 'Domain-centered',
    seedModule: 'Core domain',
    uiModuleId: 'mod.case-workspace',
    style: 'closed-loop reliability system',
    modules: [
      ['mod.case-workspace', 'Case workspace', 'experience', 'Combines failure evidence, analysis, actions, and recurrence.'],
      ['mod.failure-ledger', 'Failure ledger', 'domain', 'Owns failure reports, classifications, assets, and occurrence data.'],
      ['mod.cause-analysis', 'Cause analysis', 'domain', 'Owns hypotheses, evidence, causal links, and conclusions.'],
      ['mod.action-control', 'Action control', 'workflow', 'Owns containment, correction, verification, and overdue work.'],
      ['mod.trend-service', 'Trend service', 'platform', 'Computes Pareto, repeat rate, exposure, and recurrence signals.'],
    ],
    dependencies: [
      ['mod.case-workspace', 'mod.failure-ledger', 'The case view reads controlled failure data.'],
      ['mod.failure-ledger', 'mod.cause-analysis', 'Classified failures start causal analysis.'],
      ['mod.cause-analysis', 'mod.action-control', 'Verified causes create corrective work.'],
      ['mod.action-control', 'mod.trend-service', 'Closed actions enter recurrence monitoring.'],
    ],
  },
}

const paletteProfiles = {
  gulfstream: {
    palette: 'Gulfstream blue',
    darkCanvas: '#003767',
    darkSurface: '#063c6b',
    darkSurfaceSubtle: '#0d416f',
    darkSurfaceRaised: '#144773',
    darkBorder: '#4d7394',
    darkBorderStrong: '#809bb3',
    lightNavigation: '#003767',
    darkNavigation: '#003767',
    darkNavigationMuted: '#d8e1e9',
    darkOnAccent: '#003767',
    lightAccent: '#003767',
    darkAccent: '#ffffff',
    lightSoft: '#e2eef5',
    darkSoft: '#164a75',
    lightRgb: '0, 55, 103',
    darkRgb: '255, 255, 255',
  },
  graphite: {
    palette: 'Graphite',
    darkCanvas: '#0d1117',
    darkSurface: '#151b23',
    darkSurfaceSubtle: '#1c2430',
    darkSurfaceRaised: '#212a36',
    darkBorder: '#30363d',
    darkBorderStrong: '#59636e',
    lightNavigation: '#24292f',
    darkNavigation: '#090d12',
    darkNavigationMuted: '#b1bac4',
    darkOnAccent: '#0d1117',
    lightAccent: '#24292f',
    darkAccent: '#58a6ff',
    lightSoft: '#eaeef2',
    darkSoft: '#132f4c',
    lightRgb: '36, 41, 47',
    darkRgb: '88, 166, 255',
  },
  teal: {
    palette: 'Deep teal',
    darkCanvas: '#062a2b',
    darkSurface: '#0a3a3b',
    darkSurfaceSubtle: '#10494a',
    darkSurfaceRaised: '#185958',
    darkBorder: '#2c6866',
    darkBorderStrong: '#5b9692',
    lightNavigation: '#075e61',
    darkNavigation: '#041f20',
    darkNavigationMuted: '#b9d8d5',
    darkOnAccent: '#062a2b',
    lightAccent: '#075e61',
    darkAccent: '#62d0ca',
    lightSoft: '#e0f1f0',
    darkSoft: '#103c3d',
    lightRgb: '7, 94, 97',
    darkRgb: '98, 208, 202',
  },
  violet: {
    palette: 'Technical violet',
    darkCanvas: '#1d1438',
    darkSurface: '#2a1d4a',
    darkSurfaceSubtle: '#37265d',
    darkSurfaceRaised: '#44316d',
    darkBorder: '#5b477e',
    darkBorderStrong: '#8975ab',
    lightNavigation: '#4f3698',
    darkNavigation: '#160f2b',
    darkNavigationMuted: '#d6cced',
    darkOnAccent: '#1d1438',
    lightAccent: '#4f3698',
    darkAccent: '#b5a0f4',
    lightSoft: '#eee9f8',
    darkSoft: '#2a2245',
    lightRgb: '79, 54, 152',
    darkRgb: '181, 160, 244',
  },
  amber: {
    palette: 'Flight amber',
    darkCanvas: '#2b1d08',
    darkSurface: '#3b290d',
    darkSurfaceSubtle: '#4b3613',
    darkSurfaceRaised: '#5b441a',
    darkBorder: '#735a31',
    darkBorderStrong: '#a58a5b',
    lightNavigation: '#5a3a08',
    darkNavigation: '#211606',
    darkNavigationMuted: '#e2d0af',
    darkOnAccent: '#2b1d08',
    lightAccent: '#7a4b00',
    darkAccent: '#f0bd62',
    lightSoft: '#f8edda',
    darkSoft: '#3e2c14',
    lightRgb: '122, 75, 0',
    darkRgb: '240, 189, 98',
  },
}

const fontProfiles = {
  system: 'ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  inter: 'Inter, ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  plex: '"IBM Plex Sans", Inter, ui-sans-serif, system-ui, sans-serif',
  source: '"Source Sans 3", Inter, ui-sans-serif, system-ui, sans-serif',
  atkinson: '"Atkinson Hyperlegible", Inter, ui-sans-serif, system-ui, sans-serif',
}

const productDesignProfiles = {
  review: { paletteId: 'gulfstream', fontId: 'inter', defaultMode: 'system', density: 'compact' },
  sessions: { paletteId: 'gulfstream', fontId: 'source', defaultMode: 'dark', density: 'comfortable' },
  writing: { paletteId: 'gulfstream', fontId: 'plex', defaultMode: 'light', density: 'comfortable' },
  telemetry: { paletteId: 'gulfstream', fontId: 'inter', defaultMode: 'dark', density: 'compact' },
  trade: { paletteId: 'gulfstream', fontId: 'source', defaultMode: 'system', density: 'compact' },
  hil: { paletteId: 'gulfstream', fontId: 'plex', defaultMode: 'dark', density: 'compact' },
  supplier: { paletteId: 'gulfstream', fontId: 'atkinson', defaultMode: 'light', density: 'comfortable' },
  impact: { paletteId: 'gulfstream', fontId: 'inter', defaultMode: 'system', density: 'compact' },
  load: { paletteId: 'gulfstream', fontId: 'system', defaultMode: 'dark', density: 'compact' },
  fracas: { paletteId: 'gulfstream', fontId: 'atkinson', defaultMode: 'system', density: 'comfortable' },
}

export const productTrialSystems = productTrialSystemsBase.map((system) => {
  const profile = productDesignProfiles[system.layout]
  const palette = paletteProfiles[profile.paletteId]
  return {
  ...system,
  architecture: architecturePlans[system.slug],
  productKind: system.layout,
    design: {
      contractId: 'EUIT-FRONTEND-001',
      iconFamily: 'lucide',
      ...profile,
      ...palette,
      fontStack: fontProfiles[profile.fontId],
    },
  }
})

export function systemBySlug(slug) {
  return productTrialSystems.find((system) => system.slug === slug)
}
