/** Generated by apps/gui/scripts/generate-sample-evidence.mjs. Do not edit by hand. */
export type SampleEvidenceManifestEntry = {
  screenshot: { fileName: string; sha256: string; bytes: number; width: number; height: number }
  structured: { fileName: string; sha256: string; bytes: number }
}

export const SAMPLE_EVIDENCE_MANIFEST: Readonly<Record<string, SampleEvidenceManifestEntry>> = {
  "sample-do178c-audit-hub.use-case-analysis.use-case.browse-lifecycle.step.broken": {
    "screenshot": {
      "fileName": "01-broken-13a81cfe163c.png",
      "sha256": "8d914d14983cafdfae5d0a3a6b1e94aefe795a8396b5283a627a68b9a16858fe",
      "bytes": 151716,
      "width": 1280,
      "height": 800
    },
    "structured": {
      "fileName": "01-broken-13a81cfe163c.json",
      "sha256": "0c7d8a0bb34abe4a081fd2f1e182cdd4accd151d2f41b7904f262e432ce29f82",
      "bytes": 2646
    }
  },
  "sample-do178c-audit-hub.use-case-analysis.use-case.browse-lifecycle.step.compare": {
    "screenshot": {
      "fileName": "02-compare-7978914d79f3.png",
      "sha256": "af7d4c63675cb26fe35c99c07ba0d6630a71fee16f0fe554352d0699df11c966",
      "bytes": 153043,
      "width": 1280,
      "height": 800
    },
    "structured": {
      "fileName": "02-compare-7978914d79f3.json",
      "sha256": "b7cce82f4f5d9043ca06992633c177588a36726b9869c56dac259adf4c2148aa",
      "bytes": 2649
    }
  },
  "sample-do178c-audit-hub.use-case-analysis.use-case.browse-lifecycle.step.continue": {
    "screenshot": {
      "fileName": "03-continue-38e7b943edb6.png",
      "sha256": "769ef7f7861b428bc8859d824ff38d408c960af0a5431721fde4d95e184747d4",
      "bytes": 156241,
      "width": 1280,
      "height": 800
    },
    "structured": {
      "fileName": "03-continue-38e7b943edb6.json",
      "sha256": "3d3997d87924b7477a397622ec214a424cf8035957801a82cd36155785736ae8",
      "bytes": 2694
    }
  },
  "sample-do178c-audit-hub.use-case-analysis.use-case.browse-lifecycle.step.phase": {
    "screenshot": {
      "fileName": "04-phase-5ca78699e996.png",
      "sha256": "aeb0ac8628affc4d2c7d1ce29116949fc5f38b2a3064d5143b9aa1a3ae777ddd",
      "bytes": 146864,
      "width": 1280,
      "height": 800
    },
    "structured": {
      "fileName": "04-phase-5ca78699e996.json",
      "sha256": "c2c5275d218a24bb686a428026651df344becd5219d61f63ff0f6ce160fa9d43",
      "bytes": 2528
    }
  },
  "sample-do178c-audit-hub.use-case-analysis.use-case.browse-lifecycle.step.view": {
    "screenshot": {
      "fileName": "05-view-0f9b220b56a2.png",
      "sha256": "6af088eea4195385edf0b0107e188a558ca091073034b8ad87c93a8f3ed16de4",
      "bytes": 145723,
      "width": 1280,
      "height": 800
    },
    "structured": {
      "fileName": "05-view-0f9b220b56a2.json",
      "sha256": "03dda8d735dbc04cc60081a821356eceec0222a97b56234c241733864f362a68",
      "bytes": 2541
    }
  },
  "sample-do178c-audit-hub.use-case-analysis.use-case.browse-lifecycle.step.trace": {
    "screenshot": {
      "fileName": "06-trace-47208aa92e24.png",
      "sha256": "07489a2c0ddbad6826784f29e550a7abfcc06f3d2e48d2d0526b8859819e8719",
      "bytes": 147896,
      "width": 1280,
      "height": 800
    },
    "structured": {
      "fileName": "06-trace-47208aa92e24.json",
      "sha256": "ac5aa98fcc4d4c28ec4f64963c91369bb7df622579aace6ee2c019285385377f",
      "bytes": 2578
    }
  },
  "sample-do178c-audit-hub.use-case-analysis.use-case.export-package.step.cancel-package": {
    "screenshot": {
      "fileName": "07-cancel-package-2a03cc525f4c.png",
      "sha256": "11487781b9df33e426131e4cf646075c8b4c4fa9f50e7c408f8a5514cbec8946",
      "bytes": 149345,
      "width": 1280,
      "height": 800
    },
    "structured": {
      "fileName": "07-cancel-package-2a03cc525f4c.json",
      "sha256": "e7696ec3f78bf0f48ce5fc9bf4ffe06ce3e89c8e1e617de7563d29f0f0a60f0e",
      "bytes": 2583
    }
  },
  "sample-do178c-audit-hub.use-case-analysis.use-case.export-package.step.select": {
    "screenshot": {
      "fileName": "08-select-fe7f1b864d2b.png",
      "sha256": "82f564c6cf4e117c5c5b54a6fe9f2364030a1fc349a07b0263d16e9d699bb887",
      "bytes": 148247,
      "width": 1280,
      "height": 800
    },
    "structured": {
      "fileName": "08-select-fe7f1b864d2b.json",
      "sha256": "54a37210b992852b736d3a8d8e6b064ff7556674d7376c8e291e9428d1cede76",
      "bytes": 2568
    }
  },
  "sample-do178c-audit-hub.use-case-analysis.use-case.export-package.step.create": {
    "screenshot": {
      "fileName": "09-create-d86b011e9e4b.png",
      "sha256": "fa10b4e9f4c26b00df7577e153383cda93568a6f117598b54fc256b73ae7954d",
      "bytes": 147523,
      "width": 1280,
      "height": 800
    },
    "structured": {
      "fileName": "09-create-d86b011e9e4b.json",
      "sha256": "997bccc050e9b03f8709f8b0f2a5e237ba9a3ec45d06ccf98bac191f3ab31842",
      "bytes": 2550
    }
  },
  "sample-do178c-audit-hub.use-case-analysis.use-case.export-package.step.status": {
    "screenshot": {
      "fileName": "10-status-5d3a4b14c7f5.png",
      "sha256": "f82467d6cacf3313bfad4807dafa5fb3f7669f3819b766b182adb5b45e74317a",
      "bytes": 147174,
      "width": 1280,
      "height": 800
    },
    "structured": {
      "fileName": "10-status-5d3a4b14c7f5.json",
      "sha256": "27c3dff1f8700ccf08a8a99e4a4d59f4dd21be9e206cf16abd1f5508433e4247",
      "bytes": 2542
    }
  },
  "sample-do178c-audit-hub.use-case-analysis.use-case.export-package.step.missing": {
    "screenshot": {
      "fileName": "11-missing-f0909469a38a.png",
      "sha256": "0a9a1538c32d33d37e92bf62321f90b111b54a34a834b22d2c4508b4bb1a753b",
      "bytes": 154400,
      "width": 1280,
      "height": 800
    },
    "structured": {
      "fileName": "11-missing-f0909469a38a.json",
      "sha256": "d1d43ebf648b179817fb4407ef4beb96ede9661f942b09c734190e2c73a1041f",
      "bytes": 2658
    }
  },
  "sample-do178c-audit-hub.use-case-analysis.use-case.export-package.step.retry-package": {
    "screenshot": {
      "fileName": "12-retry-package-38dccf663e14.png",
      "sha256": "aaa49b7b643590e0c91e3a46e36d306ad4cb70ae719693dfbce00dc2d9e0a833",
      "bytes": 150918,
      "width": 1280,
      "height": 800
    },
    "structured": {
      "fileName": "12-retry-package-38dccf663e14.json",
      "sha256": "4e4ab3e8e0c207817c9ba452a25b2c6d7de85d10b7ffe04f93991232c0f37815",
      "bytes": 2630
    }
  },
  "sample-do178c-audit-hub.use-case-analysis.use-case.refresh-evidence.step.cancel": {
    "screenshot": {
      "fileName": "13-cancel-eea918ea5e9f.png",
      "sha256": "a49a00113a100e9e377f43aed2596b3f11931d760d4da86dbfd876ab1d0c267a",
      "bytes": 156526,
      "width": 1280,
      "height": 800
    },
    "structured": {
      "fileName": "13-cancel-eea918ea5e9f.json",
      "sha256": "81bdbd81da59c34e98d0f133bb4c69e1cd1703e2b4de2a1bb08a482bff154dac",
      "bytes": 2651
    }
  },
  "sample-do178c-audit-hub.use-case-analysis.use-case.refresh-evidence.step.select": {
    "screenshot": {
      "fileName": "14-select-8ef71bb75b37.png",
      "sha256": "847322576f904a86477a8bdbb605f0a2d927cd2925b508d6272eadbd72dab61d",
      "bytes": 148018,
      "width": 1280,
      "height": 800
    },
    "structured": {
      "fileName": "14-select-8ef71bb75b37.json",
      "sha256": "8bde9c54911d11fc134a64e4d3560a9b419538c77549b998f0b725bc9b3f3ce7",
      "bytes": 2557
    }
  },
  "sample-do178c-audit-hub.use-case-analysis.use-case.refresh-evidence.step.validate": {
    "screenshot": {
      "fileName": "15-validate-032acb0ad8a9.png",
      "sha256": "430a78e0bdb489352fd61efeb0254929a5c461113ae49a4fa3ebaf09a287ccb1",
      "bytes": 149005,
      "width": 1280,
      "height": 800
    },
    "structured": {
      "fileName": "15-validate-032acb0ad8a9.json",
      "sha256": "c92685fbefe479849d4fc0aa060fb008ef6de725aa3188381e5bdbf63a3eef47",
      "bytes": 2576
    }
  },
  "sample-do178c-audit-hub.use-case-analysis.use-case.refresh-evidence.step.report": {
    "screenshot": {
      "fileName": "16-report-399f794048ca.png",
      "sha256": "20723d27156419e41674584cddec5b144ce050ceb12227bc12f4d50a3e906ef4",
      "bytes": 147290,
      "width": 1280,
      "height": 800
    },
    "structured": {
      "fileName": "16-report-399f794048ca.json",
      "sha256": "85519a0b62cf06da617d8b8a2cbfb28ad9a4d6a5578a5d2072355278f4dffee6",
      "bytes": 2553
    }
  },
  "sample-do178c-audit-hub.use-case-analysis.use-case.refresh-evidence.step.retry": {
    "screenshot": {
      "fileName": "17-retry-9e6c7365ccdf.png",
      "sha256": "9715efeb17867ca94e3928b3a5facaff40810639df38d370509a10ef6d7c06af",
      "bytes": 157817,
      "width": 1280,
      "height": 800
    },
    "structured": {
      "fileName": "17-retry-9e6c7365ccdf.json",
      "sha256": "9f1199b03c2e54f97f453c17b79a14d738366703519ae3fce074c4e71205f886",
      "bytes": 2711
    }
  },
  "sample-do178c-audit-hub.use-case-analysis.use-case.refresh-evidence.step.unreachable": {
    "screenshot": {
      "fileName": "18-unreachable-44280fdb6b1b.png",
      "sha256": "697e176471d2d7f9eb44012d062c368152a7cfe32e7425f51e47dc8da6d1fd26",
      "bytes": 159669,
      "width": 1280,
      "height": 800
    },
    "structured": {
      "fileName": "18-unreachable-44280fdb6b1b.json",
      "sha256": "219bae6419c34a52fb6ef1873f3b5f36fbe54bf94ec61e4a388c148b24a6824b",
      "bytes": 2738
    }
  },
  "sample-do178c-audit-hub.use-case-analysis.use-case.review-finding.step.independent-decide": {
    "screenshot": {
      "fileName": "19-independent-decide-70bebbfc93d7.png",
      "sha256": "64f0ab8736e9c512ffff5abe290bb637ed48d5685dc6524ed9701b8ee0bb2812",
      "bytes": 150093,
      "width": 1280,
      "height": 800
    },
    "structured": {
      "fileName": "19-independent-decide-70bebbfc93d7.json",
      "sha256": "0398e4493e9ac62debe12997b07ad54f18fe7dd58a9e376bc0f753fe5cd0212d",
      "bytes": 2610
    }
  },
  "sample-do178c-audit-hub.use-case-analysis.use-case.review-finding.step.open": {
    "screenshot": {
      "fileName": "20-open-fbd7cfe6619b.png",
      "sha256": "616a0621e7202afc31259fa05e49ac00ca6aae8a5a4f2aa1ee58963bbcd80cf4",
      "bytes": 149719,
      "width": 1280,
      "height": 800
    },
    "structured": {
      "fileName": "20-open-fbd7cfe6619b.json",
      "sha256": "f74cdcb10cf96a793015aa4453d9a48d94ee4b24aaa6b9908a922ec0b4a2c861",
      "bytes": 2603
    }
  },
  "sample-do178c-audit-hub.use-case-analysis.use-case.review-finding.step.decide": {
    "screenshot": {
      "fileName": "21-decide-0cc782c28775.png",
      "sha256": "a17603ba472fc0c8513d1f643064fcd2ed145f5107f828403db50a821ab0e776",
      "bytes": 149712,
      "width": 1280,
      "height": 800
    },
    "structured": {
      "fileName": "21-decide-0cc782c28775.json",
      "sha256": "1a2c10cb77d5bea8326858ff2a8cecba0cd2af0a1ff921e7e3828f3e8ed0f797",
      "bytes": 2595
    }
  },
  "sample-do178c-audit-hub.use-case-analysis.use-case.review-finding.step.close": {
    "screenshot": {
      "fileName": "22-close-a604871b7157.png",
      "sha256": "f4ba3c2c8245ed58c86ec22f69a133bd1f4e269dc371c81f1c3cb979cdea75af",
      "bytes": 144224,
      "width": 1280,
      "height": 800
    },
    "structured": {
      "fileName": "22-close-a604871b7157.json",
      "sha256": "d79cc7fa5febad29e168984f01c631e1a200dfc629dd2404509b94ae6e104537",
      "bytes": 2502
    }
  },
  "sample-do178c-audit-hub.use-case-analysis.use-case.review-finding.step.reject": {
    "screenshot": {
      "fileName": "23-reject-2e0b7f09a4f2.png",
      "sha256": "0c459ff0e39629a11a08af7794a600d70c52167a994d74fb6c5325d245abcb73",
      "bytes": 156748,
      "width": 1280,
      "height": 800
    },
    "structured": {
      "fileName": "23-reject-2e0b7f09a4f2.json",
      "sha256": "df2ae2852ac9a72f86d3a7ad9c1094d3054589af6042b05ce7a44776f9de5ede",
      "bytes": 2678
    }
  },
  "sample-do178c-audit-hub.use-case-analysis.use-case.review-finding.step.reopen": {
    "screenshot": {
      "fileName": "24-reopen-8c07f82a1eb0.png",
      "sha256": "314caf2dc99f571b22df839b06a5a0a4b2fa1b20091cdf7b674f9e2ac0cf9b35",
      "bytes": 150640,
      "width": 1280,
      "height": 800
    },
    "structured": {
      "fileName": "24-reopen-8c07f82a1eb0.json",
      "sha256": "2480b944617c94381f0030365f7e0d0a2c5737afe215089e856c82253191d4b2",
      "bytes": 2594
    }
  }
}
