function extract_audit_hub(inputPath, outputPath)
%EXTRACT_AUDIT_HUB Read-only extraction entry point for supported lifecycle files.
% This adapter uses licensed MathWorks APIs and writes only the normalized
% JSON output path supplied by the Audit Hub. The authoritative input is
% never modified or saved.

records = {};
relationships = {};
diagnostics = {};
[~, fileName, extension] = fileparts(inputPath);
extension = lower(extension);

try
    switch extension
        case {'.slreqx', '.slmx'}
            requirementSet = slreq.load(inputPath);
            cleanup = onCleanup(@() close(requirementSet)); %#ok<NASGU>
            requirements = find(requirementSet, 'Type', 'Requirement');
            for index = 1:numel(requirements)
                requirement = requirements(index);
                identifier = string(requirement.Id);
                if strlength(identifier) == 0
                    identifier = string(requirement.SID);
                end
                record = baseRecord(identifier, string(requirement.Summary), ...
                    'requirements', 'llr', upper(extension(2:end)), inputPath);
                record.meta.description = string(requirement.Description);
                records{end + 1} = record; %#ok<AGROW>
            end

        case '.slx'
            load_system(inputPath);
            cleanup = onCleanup(@() close_system(inputPath, 0)); %#ok<NASGU>
            blocks = find_system(inputPath, 'Type', 'Block');
            for index = 1:numel(blocks)
                blockPath = string(blocks{index});
                record = baseRecord(blockPath, string(get_param(blocks{index}, 'Name')), ...
                    'design', 'model-element', 'SLX', inputPath);
                record.meta.blockType = string(get_param(blocks{index}, 'BlockType'));
                records{end + 1} = record; %#ok<AGROW>
            end

        case '.sldd'
            dictionary = Simulink.data.dictionary.open(inputPath);
            cleanup = onCleanup(@() close(dictionary)); %#ok<NASGU>
            section = getSection(dictionary, 'Design Data');
            entries = find(section);
            for index = 1:numel(entries)
                name = string(entries(index).Name);
                record = baseRecord(name, name, 'design', 'data-dictionary', 'SLDD', inputPath);
                records{end + 1} = record; %#ok<AGROW>
            end

        case {'.sldatx', '.mldatx'}
            record = baseRecord("TEST-DATA:" + string(fileName), string(fileName), ...
                'verification', 'result-set', 'SLDATX', inputPath);
            record.meta.extraction = "File identity and provenance imported. " + ...
                "Detailed result extraction depends on the configured Simulink Test release.";
            records{end + 1} = record;

        otherwise
            error('AuditHub:UnsupportedSource', 'Unsupported MATLAB source extension: %s', extension);
    end
catch exception
    diagnostic = struct( ...
        'id', "matlab:" + string(fileName), ...
        'adapterId', 'adapter.matlab-simulink', ...
        'severity', 'fatal', ...
        'code', string(exception.identifier), ...
        'message', string(exception.message), ...
        'sourcePath', string(inputPath), ...
        'retryable', true);
    diagnostics{end + 1} = diagnostic;
end

payload = struct( ...
    'adapterId', 'adapter.matlab-simulink', ...
    'evidence', {records}, ...
    'relationships', {relationships}, ...
    'reviews', {{}}, ...
    'findings', {{}}, ...
    'coverage', {{}}, ...
    'changes', {{}}, ...
    'diagnostics', {diagnostics}, ...
    'provenance', {{}});

outputDirectory = fileparts(outputPath);
if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end
fileId = fopen(outputPath, 'w', 'n', 'UTF-8');
if fileId < 0
    error('AuditHub:OutputUnavailable', 'Could not open normalized output path.');
end
cleanupFile = onCleanup(@() fclose(fileId)); %#ok<NASGU>
fprintf(fileId, '%s', jsonencode(payload, PrettyPrint=true));
end

function record = baseRecord(id, title, phase, type, sourceKind, sourcePath)
record = struct( ...
    'id', char(id), ...
    'title', char(title), ...
    'type', type, ...
    'phase', phase, ...
    'status', 'in-review', ...
    'revision', 'extracted', ...
    'sourcePath', char(sourcePath), ...
    'sourceKind', sourceKind, ...
    'hash', repmat('0', 1, 64), ...
    'modified', char(datetime('now', 'TimeZone', 'UTC', 'Format', 'yyyy-MM-dd''T''HH:mm:ss.SSSXXX')), ...
    'baseline', 'candidate', ...
    'upstream', {{}}, ...
    'downstream', {{}}, ...
    'reviewState', 'not-reviewed', ...
    'findingIds', {{}}, ...
    'provenance', 'adapter.matlab-simulink read-only extraction', ...
    'changeMark', 'unchanged', ...
    'meta', struct());
end
