/**
 * Deterministic Python virtual-file emission helpers (CAP-ERA-001 §5.3,
 * §7.2, §11.1 `python.ts`), the Python-target counterpart of `typescript.ts`.
 *
 * Pure: every function here is a total, deterministic string transform over
 * its arguments. No `node:*` import, no clock, no randomness — callers
 * supply every id, path, and version. Generated file *content* may itself
 * reference the `engineering_ui_capabilities_runtime` Python package; that is
 * a property of the emitted application-local source, not of this generator
 * module.
 */

import { ordinalCompare, sortByKey, toPosixPath, uniqueSorted } from './paths.js'

/** Default `engineering_ui_capabilities_runtime` Python package/root-module name (CAP-ERA-001 §5.3, WP4A-core). */
export const DEFAULT_PYTHON_RUNTIME_PACKAGE_NAME = 'engineering_ui_capabilities_runtime'

export type GeneratedPythonFileHeaderInput = {
  readonly generatorVersion: string
  readonly referenceProfileVersion: string
  /** Content hashes/ids of every canonical record this file was derived from (CAP-CONTRACT-026 `sourceContractHashes`). */
  readonly sourceContractHashes?: readonly string[]
}

/**
 * The do-not-edit banner every generated Python file carries (§7.2), as a
 * `#`-comment block (safe anywhere in a Python source file, unlike a module
 * docstring, which must be the first statement). Deterministic:
 * `sourceContractHashes` is deduplicated and ordinally sorted so shuffled
 * input order never changes the emitted bytes.
 */
export function generatedPythonFileHeader(input: GeneratedPythonFileHeaderInput): string {
  const hashes = uniqueSorted([...(input.sourceContractHashes ?? [])])
  const lines = [
    '# GENERATED FILE — DO NOT EDIT.',
    '#',
    `# Generated by @engineering-ui-kit/core generator ${input.generatorVersion}`,
    `# against reference profile ${input.referenceProfileVersion} (CAP-ERA-001 §7.2, §11.1).`,
    '# Regenerating this file replaces its content; hand edits are not preserved.',
    '# Ownership is tracked in `.engineering-ui/capabilities/generated-ownership.json` (CAP-CONTRACT-026).',
  ]
  if (hashes.length > 0) {
    lines.push('#', `# Source contract hashes: ${hashes.join(', ')}`)
  }
  return lines.join('\n')
}

/** A conservative, non-exhaustive-but-sufficient set of reserved Python 3 keywords a generated identifier must not collide with. */
const PYTHON_KEYWORDS = new Set([
  'False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await',
  'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except',
  'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is',
  'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try',
  'while', 'with', 'yield',
])

const PYTHON_IDENTIFIER_PATTERN = /^[A-Za-z_][A-Za-z0-9_]*$/

/** True when `name` is a syntactically valid, non-keyword, unquoted Python identifier. */
export function isValidPythonIdentifier(name: string): boolean {
  return PYTHON_IDENTIFIER_PATTERN.test(name) && !PYTHON_KEYWORDS.has(name)
}

/**
 * Sanitizes an arbitrary string into a valid, non-empty, non-keyword Python
 * identifier: illegal characters are replaced with `_`, a leading digit is
 * prefixed with `_`, and a reserved keyword is suffixed with `_`.
 */
export function sanitizePythonIdentifier(value: string): string {
  const replaced = value.replace(/[^A-Za-z0-9_]/g, '_')
  const withoutLeadingDigit = /^[0-9]/.test(replaced) ? `_${replaced}` : replaced
  const nonEmpty = withoutLeadingDigit.length > 0 ? withoutLeadingDigit : '_unnamed'
  return PYTHON_KEYWORDS.has(nonEmpty) ? `${nonEmpty}_` : nonEmpty
}

/** Splits `value` into ordinal-safe words on non-alphanumeric boundaries and case transitions. */
function splitWords(value: string): string[] {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .split(/[^A-Za-z0-9]+/)
    .filter((word) => word.length > 0)
}

/** Deterministic snake_case conversion for generated Python field/function/module names. */
export function toSnakeCase(value: string): string {
  const words = splitWords(value)
  const snake = words.map((word) => word.toLowerCase()).join('_')
  return sanitizePythonIdentifier(snake.length > 0 ? snake : 'unnamed')
}

/**
 * Deterministic dotted Python module specifier from a repo-relative `.py`
 * file path (e.g. `src/generated/orders/models.py` ->
 * `src.generated.orders.models`). Pure string arithmetic — never
 * `node:path` (forbidden in `generation/*`). Every path segment is
 * sanitized into a valid Python identifier so an arbitrary repo-relative
 * path always yields an importable dotted module name.
 */
export function pythonModuleSpecifierFromPath(filePath: string): string {
  const posix = toPosixPath(filePath)
  const withoutExtension = posix.replace(/\.py$/, '')
  const segments = withoutExtension.split('/').filter((segment) => segment.length > 0 && segment !== '.')
  const sanitized = segments.map((segment) => sanitizePythonIdentifier(segment))
  return sanitized.length > 0 ? sanitized.join('.') : '_unnamed'
}

export type PythonImportDeclarationInput = {
  readonly moduleSpecifier: string
  /** Named imports (`from moduleSpecifier import name1, name2`). Omit/empty for a bare `import moduleSpecifier`. */
  readonly names?: readonly string[]
}

/**
 * Renders a deterministic, deduplicated, ordinally sorted block of Python
 * `import`/`from ... import ...` statements: declarations are merged by
 * `moduleSpecifier`, and named imports within a declaration are deduplicated
 * and sorted.
 */
export function renderPythonImportBlock(imports: readonly PythonImportDeclarationInput[]): string {
  const merged = new Map<string, Set<string>>()
  for (const decl of imports) {
    const names = merged.get(decl.moduleSpecifier) ?? new Set<string>()
    for (const name of decl.names ?? []) names.add(name)
    merged.set(decl.moduleSpecifier, names)
  }
  const entries = sortByKey([...merged.entries()], ([moduleSpecifier]) => moduleSpecifier)
  return entries
    .map(([moduleSpecifier, names]) => {
      if (names.size === 0) return `import ${moduleSpecifier}`
      return `from ${moduleSpecifier} import ${[...names].sort(ordinalCompare).join(', ')}`
    })
    .join('\n')
}
