/**
 * Deterministic TS virtual-file emission helpers (CAP-ERA-001 §7.2, §11.1
 * `typescript.ts`), shared by `contracts.ts`, `composition.ts`, and
 * `inbound.ts`.
 *
 * Pure: every function here is a total, deterministic string transform over
 * its arguments. No `node:*` import, no clock, no randomness: callers
 * supply every id, path, and version. Generated file *content* may itself
 * reference `node:*`-dependent runtime subpaths (e.g.
 * `@engineering-ui-kit/capabilities-runtime/node`); that is a property of the
 * emitted application-local source, not of this generator module.
 */

import { ordinalCompare, sortByKey } from './paths.js'

/** A pure virtual file: a repo-relative path plus its full text content. Never written to disk here. */
export type GeneratedVirtualFile = {
  readonly path: string
  readonly contents: string
}

export const DEFAULT_RUNTIME_PACKAGE_NAME = '@engineering-ui-kit/capabilities-runtime'

export type GeneratedFileHeaderInput = {
  readonly generatorVersion: string
  readonly referenceProfileVersion: string
  /** Content hashes of every canonical record this file was derived from (CAP-CONTRACT-026 `sourceContractHashes`). */
  readonly sourceContractHashes?: readonly string[]
}

/**
 * The do-not-edit banner every generated file carries (§7.2). Deterministic:
 * `sourceContractHashes` is deduplicated and ordinally sorted so shuffled
 * input order never changes the emitted bytes.
 */
export function generatedFileHeader(input: GeneratedFileHeaderInput): string {
  const hashes = [...new Set(input.sourceContractHashes ?? [])].sort(ordinalCompare)
  const lines = [
    '/**',
    ' * GENERATED FILE: DO NOT EDIT.',
    ' *',
    ` * Generated by @engineering-ui-kit/core generator ${input.generatorVersion}`,
    ` * against reference profile ${input.referenceProfileVersion} (CAP-ERA-001 §7.2, §11.1).`,
    ' * Regenerating this file replaces its content; hand edits are not preserved.',
    ' * Ownership is tracked in `.engineering-ui/capabilities/generated-ownership.json` (CAP-CONTRACT-026).',
  ]
  if (hashes.length > 0) {
    lines.push(' *', ` * Source contract hashes: ${hashes.join(', ')}`)
  }
  lines.push(' */')
  return lines.join('\n')
}

const IDENTIFIER_PATTERN = /^[A-Za-z_$][A-Za-z0-9_$]*$/

/** True when `name` is a syntactically valid, unquoted TypeScript identifier / object-literal key. */
export function isValidIdentifier(name: string): boolean {
  return IDENTIFIER_PATTERN.test(name)
}

/** Renders an object-literal/interface member key, quoting it only when necessary. */
export function renderPropertyKey(name: string): string {
  return isValidIdentifier(name) ? name : JSON.stringify(name)
}

/** Splits `value` into ordinal-safe words on non-alphanumeric boundaries and case transitions. */
function splitWords(value: string): string[] {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .split(/[^A-Za-z0-9]+/)
    .filter((word) => word.length > 0)
}

/** Deterministic PascalCase conversion for generated type/interface/const names. */
export function toPascalCase(value: string): string {
  const words = splitWords(value)
  const pascal = words.map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase()).join('')
  return pascal.length > 0 ? pascal : 'Unnamed'
}

/** Deterministic camelCase conversion for generated variable/property names. */
export function toCamelCase(value: string): string {
  const pascal = toPascalCase(value)
  return pascal.charAt(0).toLowerCase() + pascal.slice(1)
}

/**
 * Sanitizes an arbitrary string into a valid, non-empty TypeScript
 * identifier: illegal characters are dropped, and a leading digit is
 * prefixed with `_`.
 */
export function sanitizeIdentifier(value: string): string {
  const stripped = value.replace(/[^A-Za-z0-9_$]/g, '_')
  const withoutLeadingDigit = /^[0-9]/.test(stripped) ? `_${stripped}` : stripped
  return withoutLeadingDigit.length > 0 ? withoutLeadingDigit : '_unnamed'
}

export type ImportDeclarationInput = {
  readonly moduleSpecifier: string
  /** Named imports, e.g. `Outcome` or `Outcome as RuntimeOutcome`. */
  readonly namedImports?: readonly string[]
  readonly typeOnly?: boolean
}

/**
 * Renders a deterministic, deduplicated, ordinally sorted block of `import`
 * statements: declarations are merged by `(moduleSpecifier, typeOnly)`, and
 * named imports within a declaration are deduplicated and sorted.
 */
export function renderImportBlock(imports: readonly ImportDeclarationInput[]): string {
  const merged = new Map<string, { moduleSpecifier: string; typeOnly: boolean; names: Set<string> }>()
  for (const decl of imports) {
    const typeOnly = decl.typeOnly ?? false
    const key = `${typeOnly ? 'type:' : 'value:'}${decl.moduleSpecifier}`
    const entry = merged.get(key) ?? { moduleSpecifier: decl.moduleSpecifier, typeOnly, names: new Set<string>() }
    for (const name of decl.namedImports ?? []) entry.names.add(name)
    merged.set(key, entry)
  }
  const entries = sortByKey([...merged.values()], (entry) => `${entry.moduleSpecifier} ${entry.typeOnly ? '0' : '1'}`)
  return entries
    .map((entry) => {
      const names = [...entry.names].sort(ordinalCompare)
      const specifierPrefix = entry.typeOnly ? 'import type' : 'import'
      if (names.length === 0) return `${specifierPrefix} '${entry.moduleSpecifier}'`
      return `${specifierPrefix} { ${names.join(', ')} } from '${entry.moduleSpecifier}'`
    })
    .join('\n')
}

/** Joins non-empty sections with exactly one blank line between them, ending with a single trailing newline. */
export function renderVirtualFileBody(sections: readonly string[]): string {
  const nonEmpty = sections.map((section) => section.trim()).filter((section) => section.length > 0)
  return `${nonEmpty.join('\n\n')}\n`
}

/**
 * Deterministic relative ESM module specifier from one repo-relative
 * generated-file path to another repo-relative TypeScript file path. Always
 * `.js`-suffixed (NodeNext/ESM resolution convention used throughout this
 * package) and always begins with `.` or `..` (never a bare specifier).
 * Pure string arithmetic: never `node:path` (forbidden in `generation/*`).
 */
export function relativeModuleSpecifier(fromFilePath: string, toFilePath: string): string {
  const fromDir = fromFilePath.split('/').slice(0, -1)
  const toParts = toFilePath.replace(/\.tsx?$/, '').split('/')
  let shared = 0
  while (shared < fromDir.length && shared < toParts.length - 1 && fromDir[shared] === toParts[shared]) {
    shared += 1
  }
  const ups = fromDir.length - shared
  const downs = toParts.slice(shared)
  const prefixSegments = ups === 0 ? ['.'] : Array.from({ length: ups }, () => '..')
  const joined = [...prefixSegments, ...downs].join('/')
  return `${joined}.js`
}
